import { PlayerModel } from "../models/player-model";

const database: PlayerModel[] = [
  {
    id: 1,
    name: "Lionel Messi",
    club: "Barcelona",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      Overall: 95,
      Pace: 89,
      Shooting: 94,
      Passing: 92,
      Dribbling: 96,
      Defending: 38,
      Physical: 65,
    },
  },
  {
    id: 2,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    nationality: "Portugal",
    position: "Forward",
    statistics: {
      Overall: 94,
      Pace: 90,
      Shooting: 93,
      Passing: 82,
      Dribbling: 89,
      Defending: 35,
      Physical: 80,
    },
  },
  {
    id: 3,
    name: "Vinícius Júnior",
    club: "Real Madrid",
    nationality: "Brazil",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 96,
      Shooting: 86,
      Passing: 80,
      Dribbling: 94,
      Defending: 32,
      Physical: 72,
    },
  },
  {
    id: 4,
    name: "Jude Bellingham",
    club: "Real Madrid",
    nationality: "England",
    position: "Midfielder",
    statistics: {
      Overall: 91,
      Pace: 81,
      Shooting: 85,
      Passing: 86,
      Dribbling: 88,
      Defending: 78,
      Physical: 84,
    },
  },
  {
    id: 5,
    name: "Erling Haaland",
    club: "Manchester City",
    nationality: "Norway",
    position: "Forward",
    statistics: {
      Overall: 92,
      Pace: 89,
      Shooting: 95,
      Passing: 70,
      Dribbling: 81,
      Defending: 40,
      Physical: 91,
    },
  },
  {
    id: 6,
    name: "Kevin De Bruyne",
    club: "Manchester City",
    nationality: "Belgium",
    position: "Midfielder",
    statistics: {
      Overall: 91,
      Pace: 74,
      Shooting: 86,
      Passing: 94,
      Dribbling: 88,
      Defending: 65,
      Physical: 78,
    },
  },
  {
    id: 7,
    name: "Phil Foden",
    club: "Manchester City",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 87,
      Shooting: 85,
      Passing: 84,
      Dribbling: 91,
      Defending: 56,
      Physical: 63,
    },
  },
  {
    id: 8,
    name: "Harry Kane",
    club: "Bayern Munich",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 91,
      Pace: 70,
      Shooting: 94,
      Passing: 83,
      Dribbling: 82,
      Defending: 49,
      Physical: 83,
    },
  },
  {
    id: 9,
    name: "Jamal Musiala",
    club: "Bayern Munich",
    nationality: "Germany",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 86,
      Shooting: 82,
      Passing: 84,
      Dribbling: 92,
      Defending: 58,
      Physical: 64,
    },
  },
  {
    id: 10,
    name: "Lautaro Martínez",
    club: "Inter Milan",
    nationality: "Argentina",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 82,
      Shooting: 90,
      Passing: 75,
      Dribbling: 86,
      Defending: 45,
      Physical: 84,
    },
  },
  {
    id: 11,
    name: "Nicolò Barella",
    club: "Inter Milan",
    nationality: "Italy",
    position: "Midfielder",
    statistics: {
      Overall: 87,
      Pace: 79,
      Shooting: 78,
      Passing: 85,
      Dribbling: 84,
      Defending: 79,
      Physical: 80,
    },
  },
  {
    id: 12,
    name: "Bukayo Saka",
    club: "Arsenal",
    nationality: "England",
    position: "Forward",
    statistics: {
      Overall: 89,
      Pace: 89,
      Shooting: 84,
      Passing: 82,
      Dribbling: 89,
      Defending: 60,
      Physical: 70,
    },
  },
  {
    id: 13,
    name: "Martin Ødegaard",
    club: "Arsenal",
    nationality: "Norway",
    position: "Midfielder",
    statistics: {
      Overall: 88,
      Pace: 74,
      Shooting: 82,
      Passing: 90,
      Dribbling: 88,
      Defending: 63,
      Physical: 65,
    },
  },
  {
    id: 14,
    name: "Robert Lewandowski",
    club: "Barcelona",
    nationality: "Poland",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 75,
      Shooting: 93,
      Passing: 79,
      Dribbling: 86,
      Defending: 44,
      Physical: 84,
    },
  },
  {
    id: 15,
    name: "Pedri",
    club: "Barcelona",
    nationality: "Spain",
    position: "Midfielder",
    statistics: {
      Overall: 87,
      Pace: 80,
      Shooting: 76,
      Passing: 88,
      Dribbling: 90,
      Defending: 68,
      Physical: 64,
    },
  },
  {
    id: 16,
    name: "Mohamed Salah",
    club: "Liverpool",
    nationality: "Egypt",
    position: "Forward",
    statistics: {
      Overall: 90,
      Pace: 91,
      Shooting: 89,
      Passing: 82,
      Dribbling: 89,
      Defending: 46,
      Physical: 75,
    },
  },
  {
    id: 17,
    name: "Virgil van Dijk",
    club: "Liverpool",
    nationality: "Netherlands",
    position: "Defender",
    statistics: {
      Overall: 89,
      Pace: 78,
      Shooting: 61,
      Passing: 78,
      Dribbling: 72,
      Defending: 91,
      Physical: 88,
    },
  },
  {
    id: 18,
    name: "Kylian Mbappé",
    club: "Real Madrid",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 93,
      Pace: 97,
      Shooting: 91,
      Passing: 82,
      Dribbling: 92,
      Defending: 36,
      Physical: 78,
    },
  },
  {
    id: 19,
    name: "Ousmane Dembélé",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 88,
      Pace: 94,
      Shooting: 82,
      Passing: 81,
      Dribbling: 91,
      Defending: 42,
      Physical: 66,
    },
  },
  {
    id: 20,
    name: "Achraf Hakimi",
    club: "Paris Saint-Germain",
    nationality: "Morocco",
    position: "Defender",
    statistics: {
      Overall: 86,
      Pace: 93,
      Shooting: 76,
      Passing: 82,
      Dribbling: 84,
      Defending: 79,
      Physical: 78,
    },
  },
  {
    id: 21,
    name: "Vitinha",
    club: "Paris Saint-Germain",
    nationality: "Portugal",
    position: "Midfielder",
    statistics: {
      Overall: 85,
      Pace: 78,
      Shooting: 74,
      Passing: 87,
      Dribbling: 89,
      Defending: 72,
      Physical: 69,
    },
  },
  {
    id: 22,
    name: "Marquinhos",
    club: "Paris Saint-Germain",
    nationality: "Brazil",
    position: "Defender",
    statistics: {
      Overall: 87,
      Pace: 79,
      Shooting: 58,
      Passing: 80,
      Dribbling: 74,
      Defending: 89,
      Physical: 82,
    },
  },
  {
    id: 23,
    name: "Gianluigi Donnarumma",
    club: "Paris Saint-Germain",
    nationality: "Italy",
    position: "Goalkeeper",
    statistics: {
      Overall: 89,
      Diving: 91,
      Handling: 85,
      Kicking: 79,
      Reflexes: 92,
      Speed: 52,
      Positioning: 86,
    },
  },
  {
    id: 24,
    name: "Bradley Barcola",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Forward",
    statistics: {
      Overall: 84,
      Pace: 92,
      Shooting: 79,
      Passing: 78,
      Dribbling: 87,
      Defending: 38,
      Physical: 67,
    },
  },
  {
    id: 25,
    name: "Warren Zaïre-Emery",
    club: "Paris Saint-Germain",
    nationality: "France",
    position: "Midfielder",
    statistics: {
      Overall: 83,
      Pace: 81,
      Shooting: 73,
      Passing: 82,
      Dribbling: 84,
      Defending: 76,
      Physical: 78,
    },
  },
];

export const findAllPlayers = async (): Promise<PlayerModel[]> => {
  return database;
};

export const findPlayerById = async (
  id: number,
): Promise<PlayerModel | undefined> => {
  return database.find((player) => player.id === id);
};
